version: "3.8"
services:
  frontend:
    build: .
    ports:
      - "4001:80"
    container_name: symbistay-frontend
    depends_on:
      - backend

  backend:
    ports:
      - "4000:4000"
    image: bharatm29/symbistay:v0.1
    container_name: symbistay-backend